package com.shopmilk.entities;
// default package
// Generated Jun 29, 2017 8:24:48 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import javax.persistence.Id;
import javax.persistence.Table;

import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "shopmilk")
public class User implements java.io.Serializable, UserDetails{

	private static final long serialVersionUID = 3652701442993010760L;
	@Id
	@GeneratedValue(strategy = IDENTITY)
	private Integer id;
	private String firstname;
	private String lastname;
	private String mail;
	private String password;

	public User() {
	}

	public User(String firstname,String lastname, String mail, String password) {
		this.firstname = firstname;
		this.lastname = lastname;
		this.mail = mail;
		this.password = password;
	}

	
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "firstname", nullable = false, length = 50)
	public String getFirstName() {
		return this.firstname;
	}

	public void setFirstName(String firstname) {
		this.firstname = firstname;
	}
	
	@Column(name = "lastname", nullable = false, length = 50)
	public String getLastName() {
		return this.lastname;
	}
	public void setLastName(String lastname) {
		this.lastname = lastname;
	}
	
	@Column(name = "mail", nullable = false, length = 50)
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@Column(name = "password", nullable = false, length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Override
	public Collection<? extends GrantedAuthority> getAuthorities() {
//		List<GrantedAuthority> listRole = new ArrayList<GrantedAuthority>();//thằng củ lìn nào đăng nhập cũng là admin cả nhé
//		listRole.add(new GrantedAuthority() {
//			private static final long serialVersionUID = 1L;
//
//			@Override
//			public String getAuthority() {
//				return "ADMIN";
//			}
//		});
//		return listRole;
		return null;
	}

	@Override
	public String getUsername() {
		// TODO Auto-generated method stub
		return mail;
	}

	@Override
	public boolean isAccountNonExpired() {
		// TODO Auto-generated method stub
		return true;
	}

	@Override
	public boolean isAccountNonLocked() {
		// TODO Auto-generated method stub
		return true;
	}

	@Override
	public boolean isCredentialsNonExpired() {
		// TODO Auto-generated method stub
		return true;
	}

	@Override
	public boolean isEnabled() {
		// TODO Auto-generated method stub
		return true;
	}

}
